TabacosApp/tabacos-PortalEmpleado/src/main/java/mx/gob/sat/mat/tabacos/vista/reportes/ReporteHistoricosMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.mat.tabacos.vista.reportes;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import static mx.gob.sat.mat.tabacos.constants.Constantes.ARCHIVO_PDF;
import static mx.gob.sat.mat.tabacos.constants.Constantes.EXCEL_ANTES_2007;
import mx.gob.sat.mat.tabacos.constants.enums.FileExtensionEnum;
import mx.gob.sat.mat.tabacos.constants.enums.IdentificadorProcesoEnum;
import mx.gob.sat.mat.tabacos.constants.enums.MIMETypesEnum;
import mx.gob.sat.mat.tabacos.constants.enums.ReportesTabacosEnum;
import mx.gob.sat.mat.tabacos.modelo.dto.Historico;
import mx.gob.sat.mat.tabacos.negocio.BusquedasService;
import mx.gob.sat.mat.tabacos.negocio.ReporterService;
import mx.gob.sat.mat.tabacos.negocio.excepcion.BusinessException;
import mx.gob.sat.mat.tabacos.negocio.excepcion.ReporterJasperException;
import mx.gob.sat.mat.tabacos.util.FechaUtil;
import mx.gob.sat.mat.tabacos.vista.AbstractManagedBean;
import org.apache.log4j.Logger;

import org.primefaces.component.datatable.DataTable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;


/**
 *
 * @author MMMF
 */
@Controller("reportesHistoricosMB")
@Scope(value = "view")
public class ReporteHistoricosMBean extends AbstractManagedBean {
    protected static final Logger LOGGER = Logger.getLogger(ReporteHistoricosMBean.class);
    
    private static final int ROWS_PAGE = 14;
    private int numberPage;

    public static final String ERROR = "Error";
    private List<Historico> historicos;
    private Map parameters;

    @Autowired
    private ReporterService reporterService;

    @Autowired
    private BusquedasService busquedasService;

    @PostConstruct
    public void init() {
        try {
            parameters = new HashMap();
                    
            validaAccesoProceso(IdentificadorProcesoEnum.PE_AUTORIZAR_REPORTES.getDescripcion());

            Date fechaActual = new Date();
            String fechaAct = FechaUtil.formatFecha(fechaActual, FechaUtil.FORMATO_DEFAULT);
            
            numberPage = 0;
            historicos = busquedasService.listarHistoricosContribuyente();
            //Asignacion de los parametros
            parameters.put("fechaDescarga", fechaAct);

        } catch (BusinessException bexc) {
            LOGGER.error(bexc);
            FacesMessage msg = new FacesMessage("Se ha producido un error al cargar historicos");
            FacesContext.getCurrentInstance().addMessage(null, msg);
        }
    }

    public List<Historico> getHistoricos() {
        return historicos;
    }

    public void setHistoricos(List<Historico> historicos) {
        this.historicos = historicos;
    }

    public ReporterService getReporterService() {
        return reporterService;
    }

    public void setReporterService(ReporterService reporterService) {
        this.reporterService = reporterService;
    }

    public void btnGenerarReportePDF() {
        LOGGER.info("Generando PDF Historicos");

        try {
            byte[] bytesFile;

            if (reporterService != null) {

                bytesFile = reporterService.makeReport(ReportesTabacosEnum.REPORT_HISTORICOS, ARCHIVO_PDF,
                        this.parameters, recuperaHistoricosPorPagina());

                //   Agregar metodo que genera Jasper
                generaDocumento(bytesFile, MIMETypesEnum.PDF, "reporteHistoricos", FileExtensionEnum.PDF);
            }
        } catch (ReporterJasperException e) {
            LOGGER.error(e);
            super.addErrorMessage(ERROR, e.getMessage());
        } catch (Exception e) {
            LOGGER.error(e.getMessage());
        }

    }

    private List<Historico> recuperaHistoricosPorPagina() {
        List<Historico> histPagina = null;
        final DataTable datatableHistoricos = (DataTable) FacesContext.getCurrentInstance().getViewRoot()
                .findComponent("formHist:tbHist");

        if (datatableHistoricos != null) {
            numberPage = datatableHistoricos.getPage();
            LOGGER.info("Se obtuvo numero de pagina formHist:tbHist " + numberPage);

            //Historicos por pagina
            Historico hist = null;
            int indexInicial = numberPage * ROWS_PAGE;
            int indexFinal = indexInicial + ROWS_PAGE;
            if (this.historicos != null) {
                histPagina = new ArrayList<Historico>();
                for (int i = indexInicial; i < indexFinal; i++) {
                    if (i < this.historicos.size()) {
                        hist = this.historicos.get(i);
                        histPagina.add(hist);
                    }
                }
            }
        }

        return histPagina;
    }

    public void btnGenerarReporteExcel() {
        LOGGER.info("Generando EXCEL Historico Empleados");
        try {
            byte[] bytesFile;

            if (reporterService != null) {
                bytesFile = reporterService.makeReport(ReportesTabacosEnum.REPORT_HISTORICOS, EXCEL_ANTES_2007,
                        this.parameters, recuperaHistoricosPorPagina());
                
                //   Agregar metodo que genera Jasper
                generaDocumento(bytesFile, MIMETypesEnum.EXCEL, "reporteHistoricos", FileExtensionEnum.EXCEL);
            }
        } catch (ReporterJasperException e) {
            super.addErrorMessage(ERROR, e.getMessage());
            LOGGER.error(e.getMessage());
        } catch (Exception e) {
            LOGGER.error(e.getMessage());
        }
    }
    
}

TabacosApp/tabacos-PortalEmpleado/src/main/java/mx/gob/sat/mat/tabacos/vista/reportes/ReporteMarcaManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.mat.tabacos.vista.reportes;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import mx.gob.sat.mat.tabacos.constants.enums.FileExtensionEnum;
import mx.gob.sat.mat.tabacos.constants.enums.MIMETypesEnum;
import mx.gob.sat.mat.tabacos.constants.enums.OpcionReportesEnum;
import mx.gob.sat.mat.tabacos.constants.enums.ReportesTabacosEnum;
import mx.gob.sat.mat.tabacos.modelo.dto.SelectItem;
import mx.gob.sat.mat.tabacos.modelo.dto.reportes.ReportesFiltroBase;
import mx.gob.sat.mat.tabacos.negocio.MarcaReporteService;
import mx.gob.sat.mat.tabacos.negocio.ReporteService;
import mx.gob.sat.mat.tabacos.negocio.TabacaleraService;
import mx.gob.sat.mat.tabacos.negocio.excepcion.ReporteServiceException;
import mx.gob.sat.mat.tabacos.negocio.excepcion.ServiceException;
import mx.gob.sat.mat.tabacos.negocio.excepcion.TabacaleraServiceException;
import mx.gob.sat.mat.tabacos.vista.AbstractManagedBean;
import static mx.gob.sat.mat.tabacos.vista.AbstractManagedBean.INFO;
import mx.gob.sat.mat.tabacos.vista.util.Expresiones;
import mx.gob.sat.mat.tabacos.vista.util.Utilerias;
import mx.gob.sat.mat.tabacos.vista.util.ValidaRFC;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author emmanuel
 */
@Controller("reporteMarcaMB")
@Scope(value = "view")
public class ReporteMarcaManagedBean extends AbstractManagedBean {

    private static final Logger LOGGER = Logger.getLogger(ReporteMarcaManagedBean.class);

    private static final int REPORTEPDF = 1;
    private static final int REPORTEEXCEL = 2;
    private static final int MIN_TAMANIO_RFC = 11;
    private static final String MSG_REPORTE = "No contiene información el reporte";

    @Autowired
    private ReporteService reporteService;

    @Autowired
    private MarcaReporteService marcaReposteService;

    @Autowired
    @Qualifier("tababacaleraService")
    private TabacaleraService tababacaleraService;

    private List<String> lstTabacaleras;
    private List<SelectItem> marcas;
    private String marca;
    private ReportesParametrosBase marcaFiltro;
    private boolean flgBtnReportes;

    @PostConstruct
    public void init() {
        try {
            marcaFiltro = new ReportesParametrosBase();
            marcas = reporteService.consultaCombosMarcasAutorizadas();
            obtenerLstNombreTabacaleras();
        } catch (TabacaleraServiceException ex) {
            addErrorMessage(ERROR, getMessageResourceString("msg.error.carga.informacion"));
            LOGGER.error(ex.getMessage());
        } catch (ReporteServiceException ex) {
            addErrorMessage(ERROR, getMessageResourceString("msg.error.carga.informacion"));
            LOGGER.error(ex.getMessage());
        }
    }

    private void obtenerLstNombreTabacaleras() throws TabacaleraServiceException{
        lstTabacaleras = new ArrayList<String>();
        try {
            if (tababacaleraService.buscaTabacaleras() != null && !tababacaleraService.buscaTabacaleras().isEmpty()) {
                for (int i=0;i<tababacaleraService.buscaTabacaleras().size();i++) {
                    lstTabacaleras.add(tababacaleraService.buscaTabacaleras().get(i).getRfc());
                }
            }
        } catch (TabacaleraServiceException ex) {
            LOGGER.error(ex.getMessage());
            throw new TabacaleraServiceException(ex);
        } catch (IndexOutOfBoundsException ex){
            LOGGER.error(ex.getMessage());
            throw new TabacaleraServiceException(ex);
        }
    }

    public void validaRFC() {
        if (marcaFiltro.getRfc() != null && marcaFiltro.getRfc().length() > 0) {
            if (!validaRFCExiste(marcaFiltro.getRfc())) {
                addErrorMessage(ERROR, getMessageResourceString("msg.error.rfc.invalido"));
                marcaFiltro.setRfc("");
                validaParametrosReportes();
            }
            validaParametrosReportes();
        } else {
            validaParametrosReportes();
        }
    }

    public boolean validaRFCExiste(String rfc) {
        if ((rfc != null) && (rfc.length() > 0)) {
            for (String tab : lstTabacaleras) {
                if (rfc.equals(tab)) {
                    return true;
                }
            }
        }
        return false;
    }

    public void validaParametrosReportes() {
        flgBtnReportes = validarRequeridos();
    }

    public boolean validarRequeridos() {
        boolean flgRFC = (marcaFiltro.getRfc() != null && marcaFiltro.getRfc().length() > MIN_TAMANIO_RFC);
        boolean flgFecha;
        if (!flgRFC) {
            flgFecha = (marcaFiltro.getFechainicio() != null && marcaFiltro.getFechafin() != null && validaFormatoFechas());
        } else {
            flgFecha = false;
        }
        boolean flgTipoRep = (marcaFiltro.getSeleccion() != null && marcaFiltro.getSeleccion().length() > 0);

        return ((flgTipoRep) && (flgRFC || flgFecha));
    }

    public boolean validaFormatoFechas() {

        boolean flgFechasValidas = Utilerias.isPeriodoValidoMax30dias(marcaFiltro.getFechainicio(), marcaFiltro.getFechafin());

        if (!flgFechasValidas) {
            addErrorMessage(ERROR, getMessageResourceString("msg.error.fechas.rango"));
        }

        return flgFechasValidas;
    }

    public void btnGenerarReporteMarcaPDF() {
        try {
            ReportesFiltroBase filtro = new ReportesFiltroBase();
            marcaFiltro.setFechainicio(marcaFiltro.getFechainicio());

            boolean flgRfcVacio = marcaFiltro.getRfc() == null || marcaFiltro.getRfc().isEmpty();

            if (flgRfcVacio) {
                filtro.setRfc("");
            } else {
                filtro.setRfc(marcaFiltro.getRfc());
            }
            filtro.setFechaInicio(marcaFiltro.getFechainicio());
            filtro.setFechaFin(marcaFiltro.getFechafin());
            filtro.setMarca(marca);
            filtro.setRazonSocial(reporteService.
                    consultarRazonSocial(filtro.getRfc()));

            if (!validarCasos(filtro, marcaFiltro.getSeleccion(), 1)) {
                return;
            }

            byte[] reporte = marcaReposteService.
                    makeReportMarcas(ReportesTabacosEnum.REPORT_MARCAS, filtro, REPORTEPDF);

            if (reporte != null) {
                generaDocumento(reporte, MIMETypesEnum.PDF,
                        "reporte_prueba", FileExtensionEnum.PDF);
            } else {
                addMessage(INFO, MSG_REPORTE);
            }
        } catch (ServiceException ex) {
            LOGGER.error(ex);
        } catch (ReporteServiceException ex) {
            super.addErrorMessage(ERROR, ex.getMessage());
            LOGGER.error(ex.getMessage());
        }
    }

    public void btnGenerarReporteMarcaExcel() {
        try {
            ReportesFiltroBase filtro = new ReportesFiltroBase();
            this.marcaFiltro.setFechainicio(marcaFiltro.getFechainicio());

            boolean flgRfcVacio = marcaFiltro.getRfc() == null || marcaFiltro.getRfc().isEmpty();

            if (flgRfcVacio) {
                filtro.setRfc("");
            } else {
                filtro.setRfc(marcaFiltro.getRfc());
            }

            filtro.setFechaInicio(this.marcaFiltro.getFechainicio());
            filtro.setFechaFin(this.marcaFiltro.getFechafin());
            filtro.setMarca(marca);
            filtro.setRazonSocial(reporteService.
                    consultarRazonSocial(filtro.getRfc()));

            if (!validarCasos(filtro, this.marcaFiltro.getSeleccion(), 1)) {
                return;
            }

            byte[] reporte = marcaReposteService.
                    makeReportMarcas(ReportesTabacosEnum.REPORT_MARCAS, filtro, REPORTEEXCEL);

            if (reporte != null) {
                generaDocumento(reporte, MIMETypesEnum.EXCEL,
                        "reporte_prueba", FileExtensionEnum.EXCEL);
            } else {
                addMessage(INFO, MSG_REPORTE);
            }
        } catch (ReporteServiceException e) {
            LOGGER.error(e);
            super.addErrorMessage(ERROR, e.getMessage());
        } catch (ServiceException ex) {
            LOGGER.error(ex);
            super.addErrorMessage(ERROR, ex.getMessage());
        }
    }

    public void onCaptRFC() {
        validaRFC();
        try {
            if (marcaFiltro.getRfc() != null) {
                marcas = reporteService.consultaCboMarcasAutorizadasXRfc(marcaFiltro.getRfc());
            } else {
                marcas = reporteService.consultaCombosMarcasAutorizadas();
                marca = null;
            }
        } catch (ReporteServiceException ex) {
            addErrorMessage(ERROR, getMessageResourceString("msg.error.carga.informacion"));
            getLogger().error(ex);
        }
    }

    /**
     *
     * @return
     */
    public Date getToday() {
        return new Date();
    }

    /**
     *
     * @param filtro
     * @param seleccion
     * @param opcion
     * @return
     */
    public boolean validarCasos(ReportesFiltroBase filtro, String seleccion, int opcion) {
        if (filtro.getRfc() != null && (filtro.getRfc().equals("")
                && filtro.getFechaInicio() == null
                && filtro.getFechaFin() == null)) {
            super.addErrorMessage(ERROR, "Debe ingresar RFC o fecha");
            return false;
        }

        if (filtro.getFechaInicio() != null
                && filtro.getFechaFin() == null) {
            super.addErrorMessage(ERROR, "Debe de seleccionar la fecha fin");

TabacosApp/tabacos-PortalEmpleado/src/main/webapp/pages/reportes/repcodigo.xhtml
<!DOCTYPE html>
<f:view xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:c="http://java.sun.com/jsp/jstl/core"
        xmlns:pe="http://primefaces.org/ui/extensions"
        xmlns:tbc="http://www.sat.gob.mx/tabacos">
    <html xmlns="http://www.w3.org/1999/xhtml">
        <h:head>
            <meta http-equiv="X-UA-Compatible" content="IE=11"/>
            <h:outputStylesheet library="css/" name="tabacos.css"/>
            <h:outputScript library="js/" name="tabacos.js"/>
            <style type="text/css">
                .ui-menubar   {mouseover: #ff0000; background-color: #A80000;}
                .ui-state-hover {cursor:hand;}
             </style>
        </h:head>
        <h:body>
            <p:panel id="panelDowload" header="#{tbcMsj['label.titulo.codigosfalso']}" 
                     styleClass="panel-contenedor"> 
            <h:form id="formCodigo">
                <p:tabMenu activeIndex="#{param.i}" styleClass="ui-menubar"> 
                    <p:menuitem value="#{tbcMsj['label.titulo.mcontribuyente']}" url="reptabacalera.jsf?i=0" >  
                        <f:param name="i" value="0" />
                    </p:menuitem>
                    <p:menuitem value="#{tbcMsj['label.titulo.mproveedor']}" url="repproveedor.jsf?i=1" >
                        <f:param name="i" value="1" />
                    </p:menuitem>
                    <p:menuitem value="#{tbcMsj['label.titulo.mmarca']}" url="repmarca.jsf?i=2" >  
                        <f:param name="i" value="2" />
                    </p:menuitem>
                    <p:menuitem value="#{tbcMsj['label.titulo.mcodigosfalso']}" url="repcodigo.jsf?i=3" >
                        <f:param name="i" value="3" />
                    </p:menuitem>
                    <p:menuitem value="#{tbcMsj['label.titulo.mproduccion']}" url="repProduccion.jsf?i=4" >
                        <f:param name="i" value="4" />
                    </p:menuitem>
                    <p:menuitem value="#{tbcMsj['label.titulo.mdesperdicios']}" url="repDesperdicio.jsf?i=5" >   
                        <f:param name="i" value="5" />
                    </p:menuitem>
                    <p:menuitem value="#{tbcMsj['label.titulo.mhistoricos']}" url="rephistorico.jsf?i=6" >                      
                        <f:param name="i" value="6" />
                    </p:menuitem>                                        
                </p:tabMenu>
                <p:growl id="msgs" showDetail="true" sticky="true" globalOnly="true" autoUpdate="true"/>
                <table width="800px">
                    <tr>
                        <td>
                            <table width="100%">
                                <tr width="100%">                        
                                    <td>
                                        <h:outputLabel>#{tbcMsj['label.rfc.contribuyente']}</h:outputLabel>
                                    </td>
                                    <td>
                                        <p:autoComplete id="txtRFC4" value="#{reportesCodigosMB.codigoFiltro.rfc}" widgetVar="txtRFC4"
                                                        maxlength="15" completeMethod="#{reportesCodigosMB.autocompletarRFC}">
                                            <p:ajax event="blur" listener="#{reportesCodigosMB.validaRFC}" update="formCodigo btReportePdf btReporteExcel"/>
                                        </p:autoComplete>
                                        
                                    </td>
                                </tr>
                                <tr width="100%">
                                    <td>
                                        <h:outputLabel>#{tbcMsj['label.fechainicio']}</h:outputLabel>
                                    </td>
                                    <td>
                                        <p:calendar id="finicio4" value="#{reportesCodigosMB.codigoFiltro.fechainicio}" 
                                            style="width: 10px" navigator="true" pattern="dd/MM/yyyy" locale="es"
                                            requiredMessage="#{tbcMsj['msg.fechainicial']}"
                                            effect="fadeIn" effectDuration="100" maxdate="#{reportesCodigosMB.today}" readonlyInput="true">
                                            <p:ajax event="dateSelect" listener="#{reportesCodigosMB.validaFormatoFechas}" update="ffinal4"/> 
                                        </p:calendar>                            
                                    </td>
                                </tr>
                                <tr width="100%">
                                    <td>
                                        <h:outputLabel>#{tbcMsj['label.fechafin']}</h:outputLabel>
                                    </td>
                                    <td>
                                        <p:calendar id="ffinal4" value="#{reportesCodigosMB.codigoFiltro.fechafin}" 
                                                    mindate="#{reportesCodigosMB.codigoFiltro.fechainicio}" style="width: 10px"
                                            navigator="true" pattern="dd/MM/yyyy" locale="es"
                                            requiredMessage="#{tbcMsj['msg.fechafinal']}" 
                                            effect="fadeIn" effectDuration="100" maxdate="#{reportesCodigosMB.today}" readonlyInput="true">
                                            <f:attribute name="finicial" value="#{reportesCodigosMB.codigoFiltro.fechainicio}" />
                                            <p:ajax event="dateSelect" listener="#{reportesCodigosMB.validaFormatoFechas}"/>  
                                        </p:calendar>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <h:outputLabel>#{tbcMsj['label.codigosfalsos.codigos']}</h:outputLabel>
                                    </td>
                                    <td>
                                        <p:selectOneMenu id="codigoCB" value="#{reportesCodigosMB.codigoFiltro.seleccion}" widgetVar="codigoCB"
                                            style="width: 300px">
                                            <f:selectItem itemLabel="#{tbcMsj['label.seleccione.one']}" itemValue="" />                                                            
                                            <f:selectItem itemLabel="#{tbcMsj['label.opcion.falsos']}" 
                                                    itemValue="#{tbcMsj['label.opcion.falsos.valor']}" />
                                            <f:selectItem itemLabel="#{tbcMsj['label.opcion.novalidos']}" 
                                                    itemValue="#{tbcMsj['label.opcion.novalidos.valor']}" />
                                                    <h:outputText value="#{tbcMsj['label.seleccione.one']}" />
                                            <p:ajax event="change" listener="#{reportesCodigosMB.validaParametrosReportes}" update="formCodigo"/> 
                                        </p:selectOneMenu>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <h:panelGrid columns="2"> 
                    <p:commandButton id ="btReportePdf" 
                                     value="#{tbcMsj['lbl.archivo.pdf']}" 
                                     actionListener="#{reportesCodigosMB.btnGenerarReporteCodigoPDF}" 
                                     ajax="false" 
                                     disabled="#{!reportesCodigosMB.flgBtnReportes}"
                                     styleClass="gmxPositivo"/>                    
                    <p:commandButton id ="btReporteExcel" 
                                     value="#{tbcMsj['lbl.archivo.excel']}"
                                     actionListener="#{reportesCodigosMB.btnGenerarReporteCodigoExcel}"
                                     ajax="false"
                                     disabled="#{!reportesCodigosMB.flgBtnReportes}"
                                     styleClass="gmxPositivo"/>                            
                </h:panelGrid>
            </h:form>
            </p:panel>
        </h:body>
    </html>
</f:view>